//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadosEDMMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_Experiencia_Estadisticas
    {
        public int Edad_ID { get; set; }
        public Nullable<int> Empleado_ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Anios { get; set; }
        public Nullable<int> Bajas_Laborales { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
